# ============================================================
# aide.conf - Configuración de AIDE para entorno Docker
# Al ser un entorno Docker, requiere reglas específicas y que se monte /var/lib/aide como volumen Docker persistente
# ============================================================

# --- Rutas de la base de datos ---
database_in=file:/var/lib/aide/aide.db
database_out=file:/var/lib/aide/aide.db.new

# --- Nivel de log y salida ---
log_level=warning
report_url=stdout

# --- Grupos de atributos reutilizables ---
# Comprobación completa: permisos + inodo + propietario + tamaño + timestamps + hashes
FULL    = p+i+n+u+g+s+m+c+md5+sha256

# Solo permisos y propietario (para ficheros que solo cambian de contenido)
PERMS   = p+i+u+g
# Solo existencia del fichero
EXISTS  = p


# --- Binarios del sistema ---
/bin                            FULL
/sbin                           FULL
/usr/bin                        FULL
/usr/sbin                       FULL
/usr/local/apache2/bin          FULL
/usr/local/apache2/modules      FULL

# --- Script de backup
/usr/local/bin/backup_posts.py  FULL

# Carpeta de usuario
/home/wiredl4bs                 FULL

# --- Librerías del sistema ---
/lib                            FULL
/lib64                          FULL
/usr/lib                        FULL

# --- Ficheros de configuración de importancia ---
/etc/passwd                     FULL
/etc/shadow                     FULL
/etc/group                      FULL
/etc/sudoers                    FULL
/etc/ssh/sshd_config            FULL
/etc/php                        FULL
/etc/aide/aide.conf             FULL

# --- Configuración de Apache ---
/usr/local/apache2/conf         FULL

# --- Contenido web (detecta webshells, modificaciones de ficheros PHP, etc.) ---
/var/www/html                   FULL

# --- Excluimos explícitamente el directorio de posts ya que se gestiona por la web
!/var/www/html/posts

# --- Fichero de credenciales htpasswd ---
/var/www/html/restricted/users  FULL

# EXCLUSIONES OBLIGATORIAS EN DOCKER
# Estos paths cambian constantemente y generarían falsos positivos
!/proc
!/sys
!/dev
!/run
!/tmp
!/var/run
!/var/log
!/var/lib/aide
!/var/lib/php/sessions
!/var/cache
!/var/backups
